version: "3.7"
services:
  keycloak:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: keycloak
    ports:
      - "7080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_VENDOR=h2
      # if true, the code in ./data-setup is executed to initialize the realms etc.
      - POPULATE_TEST_DATA=false
